#!/bin/bash

echo "🚀 Render Deployment Script"
echo "==========================="

echo "📋 Follow these steps to deploy on Render:"
echo ""
echo "1. 🌐 Go to https://render.com"
echo "2. 🔐 Sign up/Login with GitHub"
echo "3. ➕ Click 'New +' → 'Web Service'"
echo "4. 🔗 Connect your GitHub repo: https://github.com/itsyosefali/exams_monitor_bot"
echo "5. 📝 Fill in the details:"
echo "   - Name: exams-monitor-bot"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "6. 🔧 Add Environment Variables:"
echo "   - TELEGRAM_BOT_TOKEN=your_bot_token"
echo "   - SUPABASE_URL=your_supabase_url"
echo "   - SUPABASE_ANON_KEY=your_supabase_key"
echo "   - NOTIFICATION_HOURS_BEFORE=24"
echo "   - NOTIFICATION_HOURS_BEFORE_CRITICAL=2"
echo "7. 🚀 Click 'Create Web Service'"
echo ""

echo "✅ After deployment, your bot will be available at:"
echo "   https://your-app-name.onrender.com"
echo ""
echo "📱 Test your bot by sending /start on Telegram!"
echo ""
echo "💡 Note: Render will sleep after 15 minutes of inactivity"
echo "   But it will wake up automatically when someone uses the bot"
