services:
  - type: web
    name: exams-monitor-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NOTIFICATION_HOURS_BEFORE
        value: 24
      - key: NOTIFICATION_HOURS_BEFORE_CRITICAL
        value: 2
